[build]
base = "01 - Monster Relodex"
publish = "01 - Monster Relodex/dist/"
command = "yarn build"

[build]
base = "02 - Pokodex"
publish = "02 - Pokodex/dist/"
command = "yarn build"

[build]
base = "03 - Github Finder"
publish = "03 - Github Finder/dist/"
command = "yarn build"

[build]
base = "04 - Instaish"
publish = "04 - Instaish/dist/"
command = "yarn build"